  export interface AttributeDtoList {
    IsSystemGenerated: boolean
    DtoState: number
    RequestAttributeId: number
    RequestId: number
    Name: string
    IsRequired: boolean
    Value: string
    AttributeTypeId: number
    AttributeGroupId: number
    IsRequesterVisible: boolean
    IsProviderVisible: boolean
    IsRequesterEditable: boolean
    IsProviderEditable: boolean
    RequestStepId: number
    SequenceNo: number
    IsComputed: boolean
    Formula: string
    SourceServiceAttributeId: number
    Group: string
    GroupSequenceNo: number
    ExtendedValue: string
    GroupId: number
    AttachmentOriginalName: string
    AlternateName: string
    AlternateValue: string
    AlternateGroup: string
    Alias: string
    PlaceHolder: string
    ShowInReport: boolean
    Description: string
    AlternateDescription: string
    AlternatePlaceHolder: string
    Prefix: string
    IsFiltered: boolean
    FilterAttributeAlias: string
    IsParameter: boolean
    Extra1: string
    Extra2: string
    BatchId: number
    IsComputedInitialValue: boolean
    InitialValueFormula: string
    IsValidationEnabled: boolean
    ValidationRule: string
    ValidationRuleFailedComment: string
    IsIntegrationEditable: boolean
    IsRequiredCondition: string
    OnChangeRecalculate: boolean
    PageNumber: number
    AttributeTypeValueTypeName: string
    FormatCategoryId: number
    FormatTypeName: string
    Hint: string
    HideLabel: boolean
    IsIntegration: boolean
    IsRecord: boolean
    IsRecordName: boolean
    Regex: string
    ReturnType: string
    CounterMaxValue: string
    CounterMinValue: string
    CounterStepValue: string
    HideValue: boolean
    IsPicker: boolean
    AttributeLength: string
    ShowInQuestionnaire: boolean
    IsMultipleChoice: boolean
    AttributeDefinition: string
    IsPasswordMask: boolean
    IsEncryptionEnabled: boolean
    AllowOthers: boolean
    UseGridControl: boolean
    UIControlAlias: string
    ShowInProfile: boolean
    ObjectType: number
    DocumentId: number
    FormatTypeId: number
    Translations: string
    DescriptionTranslations: string
    PlaceHolderTranslations: string
    ValueTranslations: string
    ValidationRuleFailedCommentTranslation: string
    GroupTranslations: string
    HintTranslations: string
    IsProfileDocument: boolean
    IsRequesterEditableCondition: string
    IsProviderEditableCondition: string
    IsResetIf: boolean
    ResetIfFormula: string
    FullFilePath: string
    CopyToRequest: boolean
    UseInService: boolean
    IsPhantomVisible: boolean
    IsAsynchronousIntegration: boolean
    ApplyToExisting: boolean
    FullImagePath: string,
    ValidationError?: boolean
  }
  